# This is an example Conda environment, for local development
name: pyd-yaml
channels:
  - conda-forge
dependencies:
  - python=3.8 # docs need 3.8
  - pip
  - pip:
      - -e ".[dev,docs]"
      - pydantic>=2.0.0
