# This is an example Conda environment, for local development
name: pyd-yaml
channels:
  - conda-forge
dependencies:
  - python=3.7 # minimum targeted version is currently 3.7
  - pip
  - pip:
      - -e ".[dev,docs,ruamel]"
