# This is an example Conda environment, for local development
name: pyd-yaml
channels:
  - conda-forge
dependencies:
  - python=3.8 # minimum targeted version is currently 3.7, but docs need 3.8
  - pip
  - pip:
      - -e ".[dev,docs]"
